// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PageDocumentDataSlicesSlice = HeaderSlice | HeroSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
	/**
	 * Title field in *Page*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;

	/**
	 * Slice Zone field in *Page*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
	 * Meta Title field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: page.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: page.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *Page*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<PageDocumentData>,
	'page',
	Lang
>;

/**
 * Item in *Settings → Navigation*
 */
export interface SettingsDocumentDataNavigationItem {
	/**
	 * Link field in *Settings → Navigation*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.navigation[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;

	/**
	 * Label field in *Settings → Navigation*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.navigation[].label
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	label: prismic.KeyTextField;
}

/**
 * Item in *Settings → Actions*
 */
export interface SettingsDocumentDataActionsItem {
	/**
	 * Label field in *Settings → Actions*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.actions[].label
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	label: prismic.KeyTextField;

	/**
	 * Link field in *Settings → Actions*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.actions[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;
}

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
	/**
	 * Meta Title field in *Settings*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.meta_title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *Settings*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.meta_description
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *Settings*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.meta_image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;

	/**
	 * Navigation field in *Settings*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.navigation[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	navigation: prismic.GroupField<Simplify<SettingsDocumentDataNavigationItem>>;

	/**
	 * Center Nav field in *Settings*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: settings.center_nav
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	center_nav: prismic.BooleanField;

	/**
	 * Actions field in *Settings*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.actions[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	actions: prismic.GroupField<Simplify<SettingsDocumentDataActionsItem>>;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<SettingsDocumentData>,
	'settings',
	Lang
>;

export type AllDocumentTypes = PageDocument | SettingsDocument;

/**
 * Item in *Header → Default → Primary → Links*
 */
export interface HeaderSliceDefaultPrimaryLinksItem {
	/**
	 * Text field in *Header → Default → Primary → Links*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: header.default.primary.links[].text
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	text: prismic.KeyTextField;

	/**
	 * link field in *Header → Default → Primary → Links*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: header.default.primary.links[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;

	/**
	 * Button field in *Header → Default → Primary → Links*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: header.default.primary.links[].button
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	button: prismic.BooleanField;

	/**
	 * Button Variant field in *Header → Default → Primary → Links*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: primary
	 * - **API ID Path**: header.default.primary.links[].button_variant
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	button_variant: prismic.SelectField<'primary' | 'secondary', 'filled'>;
}

/**
 * Primary content in *Header → Default → Primary*
 */
export interface HeaderSliceDefaultPrimary {
	/**
	 * Logo field in *Header → Default → Primary*
	 *
	 * - **Field Type**: Link to Media
	 * - **Placeholder**: *None*
	 * - **API ID Path**: header.default.primary.logo
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	logo: prismic.LinkToMediaField;

	/**
	 * Links field in *Header → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: header.default.primary.links[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	links: prismic.GroupField<Simplify<HeaderSliceDefaultPrimaryLinksItem>>;
}

/**
 * Default variation for Header Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<HeaderSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Header*
 */
type HeaderSliceVariation = HeaderSliceDefault;

/**
 * Header Shared Slice
 *
 * - **API ID**: `header`
 * - **Description**: Header
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderSlice = prismic.SharedSlice<'header', HeaderSliceVariation>;

/**
 * Item in *Hero → Default → Primary → Actions*
 */
export interface HeroSliceDefaultPrimaryActionsItem {
	/**
	 * title field in *Hero → Default → Primary → Actions*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.actions[].title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * link field in *Hero → Default → Primary → Actions*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.actions[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;

	/**
	 * variant field in *Hero → Default → Primary → Actions*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: primary
	 * - **API ID Path**: hero.default.primary.actions[].variant
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	variant: prismic.SelectField<'primary' | 'secondary', 'filled'>;
}

/**
 * Item in *Hero → FullBackgroundImage → Primary → Actions*
 */
export interface HeroSliceFullBackgroundImagePrimaryActionsItem {
	/**
	 * title field in *Hero → FullBackgroundImage → Primary → Actions*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.fullBackgroundImage.primary.actions[].title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * link field in *Hero → FullBackgroundImage → Primary → Actions*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.fullBackgroundImage.primary.actions[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;

	/**
	 * variant field in *Hero → FullBackgroundImage → Primary → Actions*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: primary
	 * - **API ID Path**: hero.fullBackgroundImage.primary.actions[].variant
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	variant: prismic.SelectField<'primary' | 'secondary', 'filled'>;
}

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
	/**
	 * Header field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: A Beautiful Header Goes Here!
	 * - **API ID Path**: hero.default.primary.header
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	header: prismic.TitleField;

	/**
	 * Body field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: This is a generic amount of body text that should live in the header
	 * - **API ID Path**: hero.default.primary.body
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	body: prismic.RichTextField;

	/**
	 * BG Image field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.bg_image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	bg_image: prismic.ImageField<never>;

	/**
	 * Actions field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.actions[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	actions: prismic.GroupField<Simplify<HeroSliceDefaultPrimaryActionsItem>>;

	/**
	 * reversed field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: hero.default.primary.reversed
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	reversed: prismic.BooleanField;

	/**
	 * Input Label field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.input_label
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	input_label: prismic.KeyTextField;

	/**
	 * Input Action field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.input_action
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	input_action: prismic.KeyTextField;

	/**
	 * Input Placeholder field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.input_placeholder
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	input_placeholder: prismic.KeyTextField;

	/**
	 * Input CTA field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.input_cta
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	input_cta: prismic.KeyTextField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<HeroSliceDefaultPrimary>,
	never
>;

/**
 * Primary content in *Hero → FullBackgroundImage → Primary*
 */
export interface HeroSliceFullBackgroundImagePrimary {
	/**
	 * Header field in *Hero → FullBackgroundImage → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: A Beautiful Header Goes Here!
	 * - **API ID Path**: hero.fullBackgroundImage.primary.header
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	header: prismic.TitleField;

	/**
	 * Body field in *Hero → FullBackgroundImage → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: This is a generic amount of body text that should live in the header
	 * - **API ID Path**: hero.fullBackgroundImage.primary.body
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	body: prismic.RichTextField;

	/**
	 * BG Image field in *Hero → FullBackgroundImage → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.fullBackgroundImage.primary.bg_image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	bg_image: prismic.ImageField<never>;

	/**
	 * Actions field in *Hero → FullBackgroundImage → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.fullBackgroundImage.primary.actions[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	actions: prismic.GroupField<Simplify<HeroSliceFullBackgroundImagePrimaryActionsItem>>;

	/**
	 * reversed field in *Hero → FullBackgroundImage → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: hero.fullBackgroundImage.primary.reversed
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	reversed: prismic.BooleanField;

	/**
	 * Input Label field in *Hero → FullBackgroundImage → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.fullBackgroundImage.primary.input_label
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	input_label: prismic.KeyTextField;

	/**
	 * Input Action field in *Hero → FullBackgroundImage → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.fullBackgroundImage.primary.input_action
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	input_action: prismic.KeyTextField;

	/**
	 * Input Placeholder field in *Hero → FullBackgroundImage → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.fullBackgroundImage.primary.input_placeholder
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	input_placeholder: prismic.KeyTextField;

	/**
	 * Input CTA field in *Hero → FullBackgroundImage → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.fullBackgroundImage.primary.input_cta
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	input_cta: prismic.KeyTextField;
}

/**
 * FullBackgroundImage variation for Hero Slice
 *
 * - **API ID**: `fullBackgroundImage`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceFullBackgroundImage = prismic.SharedSliceVariation<
	'fullBackgroundImage',
	Simplify<HeroSliceFullBackgroundImagePrimary>,
	never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault | HeroSliceFullBackgroundImage;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<'hero', HeroSliceVariation>;

declare module '@prismicio/client' {
	interface CreateClient {
		(
			repositoryNameOrEndpoint: string,
			options?: prismic.ClientConfig
		): prismic.Client<AllDocumentTypes>;
	}

	namespace Content {
		export type {
			PageDocument,
			PageDocumentData,
			PageDocumentDataSlicesSlice,
			SettingsDocument,
			SettingsDocumentData,
			SettingsDocumentDataNavigationItem,
			SettingsDocumentDataActionsItem,
			AllDocumentTypes,
			HeaderSlice,
			HeaderSliceDefaultPrimaryLinksItem,
			HeaderSliceDefaultPrimary,
			HeaderSliceVariation,
			HeaderSliceDefault,
			HeroSlice,
			HeroSliceDefaultPrimaryActionsItem,
			HeroSliceDefaultPrimary,
			HeroSliceFullBackgroundImagePrimaryActionsItem,
			HeroSliceFullBackgroundImagePrimary,
			HeroSliceVariation,
			HeroSliceDefault,
			HeroSliceFullBackgroundImage
		};
	}
}
